### PR TITLE
LGA-3290: Add Welsh translation to the maintenance page.

### PR DESCRIPTION
**Pull request by BenMillar-MOJ**
### Adds the Welsh translation to the maintenance page
Screenshot 2024-10-11 at 17 54 06

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by digitalali-moj — APPROVED** [review]
LGTM! Thanks :)

**Review by TawneeOwl — APPROVED** [review]
LGTM

**Comment by said-moj** [comment]
Is it possible to remove the line numbers from the translated file. This causes alot of change in future PRs if the text in source file is moved to another line

I think https://github.com/ministryofjustice/laa-access-civil-legal-aid/blob/main/bin/translate.sh#L6 needs an ` --no-location` passed into it https://babel.pocoo.org/en/latest/cmdline.html#extract

**Comment by BenMillar-MOJ** [comment]
> Is it possible to remove the line numbers from the translated file. This causes alot of change in future PRs if the text in source file is moved to another line
> 
> I think https://github.com/ministryofjustice/laa-access-civil-legal-aid/blob/main/bin/translate.sh#L6 needs an ` --no-location` passed into it https://babel.pocoo.org/en/latest/cmdline.html#extract

Thanks @said-moj I have fixed this with this commit!

**Review by said-moj — APPROVED** [review]

**Pull request merged**
